[2023-10-08T21:08:05.756+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-08T21:02:58.565715+00:00 [queued]>
[2023-10-08T21:08:05.784+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-08T21:02:58.565715+00:00 [queued]>
[2023-10-08T21:08:05.785+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-10-08T21:08:05.932+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): upload_to_s3> on 2023-10-08 21:02:58.565715+00:00
[2023-10-08T21:08:06.008+0000] {standard_task_runner.py:57} INFO - Started process 199 to run task
[2023-10-08T21:08:06.044+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extract_job_data_in_selenium_container', 'upload_to_s3', 'manual__2023-10-08T21:02:58.565715+00:00', '--job-id', '501', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmp7_jkxqtn']
[2023-10-08T21:08:06.049+0000] {standard_task_runner.py:85} INFO - Job 501: Subtask upload_to_s3
[2023-10-08T21:08:06.224+0000] {task_command.py:410} INFO - Running <TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-08T21:02:58.565715+00:00 [running]> on host cae9180efd34
[2023-10-08T21:08:06.676+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extract_job_data_in_selenium_container' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-10-08T21:02:58.565715+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-08T21:02:58.565715+00:00'
[2023-10-08T21:08:06.678+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-08T21:08:06.678+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/extraction/upload_aws_s3_etl.py 20231008']
[2023-10-08T21:08:06.700+0000] {subprocess.py:86} INFO - Output:
[2023-10-08T21:08:06.824+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/extraction/upload_aws_s3_etl.py': [Errno 2] No such file or directory
[2023-10-08T21:08:06.829+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-08T21:08:06.842+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-08T21:08:06.847+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=Extract_job_data_in_selenium_container, task_id=upload_to_s3, execution_date=20231008T210258, start_date=20231008T210805, end_date=20231008T210806
[2023-10-08T21:08:06.863+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 501 for task upload_to_s3 (Bash command failed. The command returned a non-zero exit code 2.; 199)
[2023-10-08T21:08:06.902+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-08T21:08:07.891+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
