[2023-10-09T02:14:33.502+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-09T02:14:32.371385+00:00 [queued]>
[2023-10-09T02:14:33.518+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-09T02:14:32.371385+00:00 [queued]>
[2023-10-09T02:14:33.519+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-10-09T02:14:33.543+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): upload_to_s3> on 2023-10-09 02:14:32.371385+00:00
[2023-10-09T02:14:33.551+0000] {standard_task_runner.py:57} INFO - Started process 95 to run task
[2023-10-09T02:14:33.557+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extract_job_data_in_selenium_container', 'upload_to_s3', 'manual__2023-10-09T02:14:32.371385+00:00', '--job-id', '608', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmp7b9_hj38']
[2023-10-09T02:14:33.559+0000] {standard_task_runner.py:85} INFO - Job 608: Subtask upload_to_s3
[2023-10-09T02:14:33.650+0000] {task_command.py:410} INFO - Running <TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-09T02:14:32.371385+00:00 [running]> on host e12c8be37a23
[2023-10-09T02:14:33.818+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extract_job_data_in_selenium_container' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-10-09T02:14:32.371385+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-09T02:14:32.371385+00:00'
[2023-10-09T02:14:33.820+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-09T02:14:33.820+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/extraction/upload_aws_s3_etl.py 20231009']
[2023-10-09T02:14:33.836+0000] {subprocess.py:86} INFO - Output:
[2023-10-09T02:14:33.951+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/extraction/upload_aws_s3_etl.py': [Errno 2] No such file or directory
[2023-10-09T02:14:33.956+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-09T02:14:33.975+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-09T02:14:33.981+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Extract_job_data_in_selenium_container, task_id=upload_to_s3, execution_date=20231009T021432, start_date=20231009T021433, end_date=20231009T021433
[2023-10-09T02:14:34.003+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 608 for task upload_to_s3 (Bash command failed. The command returned a non-zero exit code 2.; 95)
[2023-10-09T02:14:34.049+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-09T02:14:34.072+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
