[2023-10-08T22:54:21.776+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-08T22:49:19.127581+00:00 [queued]>
[2023-10-08T22:54:21.791+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-08T22:49:19.127581+00:00 [queued]>
[2023-10-08T22:54:21.791+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-10-08T22:54:21.811+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): upload_to_s3> on 2023-10-08 22:49:19.127581+00:00
[2023-10-08T22:54:21.817+0000] {standard_task_runner.py:57} INFO - Started process 590 to run task
[2023-10-08T22:54:21.822+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extract_job_data_in_selenium_container', 'upload_to_s3', 'manual__2023-10-08T22:49:19.127581+00:00', '--job-id', '545', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmp845skyg7']
[2023-10-08T22:54:21.824+0000] {standard_task_runner.py:85} INFO - Job 545: Subtask upload_to_s3
[2023-10-08T22:54:21.888+0000] {task_command.py:410} INFO - Running <TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-08T22:49:19.127581+00:00 [running]> on host 567643eabf3d
[2023-10-08T22:54:21.997+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extract_job_data_in_selenium_container' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-10-08T22:49:19.127581+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-08T22:49:19.127581+00:00'
[2023-10-08T22:54:21.999+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-08T22:54:22.000+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/extraction/upload_aws_s3_etl.py 20231008']
[2023-10-08T22:54:22.016+0000] {subprocess.py:86} INFO - Output:
[2023-10-08T22:54:22.129+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/extraction/upload_aws_s3_etl.py': [Errno 2] No such file or directory
[2023-10-08T22:54:22.134+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-08T22:54:22.147+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-08T22:54:22.153+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=Extract_job_data_in_selenium_container, task_id=upload_to_s3, execution_date=20231008T224919, start_date=20231008T225421, end_date=20231008T225422
[2023-10-08T22:54:22.180+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 545 for task upload_to_s3 (Bash command failed. The command returned a non-zero exit code 2.; 590)
[2023-10-08T22:54:22.194+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-08T22:54:22.219+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
