[2023-11-02T20:45:53.831+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_Job_Listings_Data_Pipeline.feature_engineering manual__2023-11-02T20:39:56.149547+00:00 [queued]>
[2023-11-02T20:45:53.843+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_Job_Listings_Data_Pipeline.feature_engineering manual__2023-11-02T20:39:56.149547+00:00 [queued]>
[2023-11-02T20:45:53.844+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-11-02T20:45:53.862+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): feature_engineering> on 2023-11-02 20:39:56.149547+00:00
[2023-11-02T20:45:53.867+0000] {standard_task_runner.py:57} INFO - Started process 280 to run task
[2023-11-02T20:45:53.872+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Google_Job_Listings_Data_Pipeline', 'feature_engineering', 'manual__2023-11-02T20:39:56.149547+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmp0lvkh3bt']
[2023-11-02T20:45:53.874+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask feature_engineering
[2023-11-02T20:45:53.934+0000] {task_command.py:410} INFO - Running <TaskInstance: Google_Job_Listings_Data_Pipeline.feature_engineering manual__2023-11-02T20:39:56.149547+00:00 [running]> on host 1f525f761703
[2023-11-02T20:45:54.026+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Google_Job_Listings_Data_Pipeline' AIRFLOW_CTX_TASK_ID='feature_engineering' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T20:39:56.149547+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-02T20:39:56.149547+00:00'
[2023-11-02T20:45:54.027+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-02T20:45:54.028+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/extraction/feature_engineering.py 20231102']
[2023-11-02T20:45:54.043+0000] {subprocess.py:86} INFO - Output:
[2023-11-02T20:45:55.313+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-02T20:45:55.313+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/feature_engineering.py", line 15, in <module>
[2023-11-02T20:45:55.314+0000] {subprocess.py:93} INFO -     df = pd.read_csv(f"../tmp/{output_name}.csv")
[2023-11-02T20:45:55.314+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2023-11-02T20:45:55.316+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-11-02T20:45:55.317+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
[2023-11-02T20:45:55.319+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2023-11-02T20:45:55.320+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
[2023-11-02T20:45:55.321+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2023-11-02T20:45:55.322+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
[2023-11-02T20:45:55.323+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(self.engine)
[2023-11-02T20:45:55.324+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
[2023-11-02T20:45:55.324+0000] {subprocess.py:93} INFO -     return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
[2023-11-02T20:45:55.325+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
[2023-11-02T20:45:55.326+0000] {subprocess.py:93} INFO -     self._open_handles(src, kwds)
[2023-11-02T20:45:55.326+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
[2023-11-02T20:45:55.327+0000] {subprocess.py:93} INFO -     errors=kwds.get("encoding_errors", "strict"),
[2023-11-02T20:45:55.327+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
[2023-11-02T20:45:55.328+0000] {subprocess.py:93} INFO -     newline="",
[2023-11-02T20:45:55.328+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '../tmp/20231102.csv'
[2023-11-02T20:45:55.479+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-02T20:45:55.512+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-02T20:45:55.522+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=Google_Job_Listings_Data_Pipeline, task_id=feature_engineering, execution_date=20231102T203956, start_date=20231102T204553, end_date=20231102T204555
[2023-11-02T20:45:55.554+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 54 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 280)
[2023-11-02T20:45:55.610+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-11-02T20:45:55.652+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
