[2023-10-08T21:27:24.922+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-08T21:27:22.971445+00:00 [queued]>
[2023-10-08T21:27:24.936+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-08T21:27:22.971445+00:00 [queued]>
[2023-10-08T21:27:24.937+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-10-08T21:27:24.961+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): upload_to_s3> on 2023-10-08 21:27:22.971445+00:00
[2023-10-08T21:27:24.971+0000] {standard_task_runner.py:57} INFO - Started process 611 to run task
[2023-10-08T21:27:24.977+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extract_job_data_in_selenium_container', 'upload_to_s3', 'manual__2023-10-08T21:27:22.971445+00:00', '--job-id', '517', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmpa7h_tjq3']
[2023-10-08T21:27:24.978+0000] {standard_task_runner.py:85} INFO - Job 517: Subtask upload_to_s3
[2023-10-08T21:27:25.063+0000] {task_command.py:410} INFO - Running <TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-08T21:27:22.971445+00:00 [running]> on host cae9180efd34
[2023-10-08T21:27:25.212+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extract_job_data_in_selenium_container' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-10-08T21:27:22.971445+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-08T21:27:22.971445+00:00'
[2023-10-08T21:27:25.214+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-08T21:27:25.217+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/extraction/upload_aws_s3_etl.py 20231008']
[2023-10-08T21:27:25.236+0000] {subprocess.py:86} INFO - Output:
[2023-10-08T21:27:25.362+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/extraction/upload_aws_s3_etl.py': [Errno 2] No such file or directory
[2023-10-08T21:27:25.366+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-08T21:27:25.383+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-08T21:27:25.391+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Extract_job_data_in_selenium_container, task_id=upload_to_s3, execution_date=20231008T212722, start_date=20231008T212724, end_date=20231008T212725
[2023-10-08T21:27:25.427+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 517 for task upload_to_s3 (Bash command failed. The command returned a non-zero exit code 2.; 611)
[2023-10-08T21:27:25.470+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-08T21:27:25.524+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
