[2023-10-09T21:13:27.224+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-09T21:13:25.476538+00:00 [queued]>
[2023-10-09T21:13:27.241+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-09T21:13:25.476538+00:00 [queued]>
[2023-10-09T21:13:27.242+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-10-09T21:13:27.265+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): upload_to_s3> on 2023-10-09 21:13:25.476538+00:00
[2023-10-09T21:13:27.271+0000] {standard_task_runner.py:57} INFO - Started process 136 to run task
[2023-10-09T21:13:27.277+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extract_job_data_in_selenium_container', 'upload_to_s3', 'manual__2023-10-09T21:13:25.476538+00:00', '--job-id', '719', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmp4r7rnz7u']
[2023-10-09T21:13:27.279+0000] {standard_task_runner.py:85} INFO - Job 719: Subtask upload_to_s3
[2023-10-09T21:13:27.344+0000] {task_command.py:410} INFO - Running <TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-09T21:13:25.476538+00:00 [running]> on host 18e533bd1f06
[2023-10-09T21:13:27.465+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extract_job_data_in_selenium_container' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-10-09T21:13:25.476538+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-09T21:13:25.476538+00:00'
[2023-10-09T21:13:27.467+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-09T21:13:27.469+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/extraction/upload_aws_s3_etl.py 20231009']
[2023-10-09T21:13:27.484+0000] {subprocess.py:86} INFO - Output:
[2023-10-09T21:13:27.611+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/extraction/upload_aws_s3_etl.py': [Errno 2] No such file or directory
[2023-10-09T21:13:27.615+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-09T21:13:27.631+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-09T21:13:27.637+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Extract_job_data_in_selenium_container, task_id=upload_to_s3, execution_date=20231009T211325, start_date=20231009T211327, end_date=20231009T211327
[2023-10-09T21:13:27.655+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 719 for task upload_to_s3 (Bash command failed. The command returned a non-zero exit code 2.; 136)
[2023-10-09T21:13:27.690+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-09T21:13:27.749+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
