[2023-11-02T20:38:13.367+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Google_Job_Listings_Data_Pipeline.feature_engineering manual__2023-11-02T20:36:53.997826+00:00 [queued]>
[2023-11-02T20:38:13.380+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Google_Job_Listings_Data_Pipeline.feature_engineering manual__2023-11-02T20:36:53.997826+00:00 [queued]>
[2023-11-02T20:38:13.381+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-11-02T20:38:13.400+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): feature_engineering> on 2023-11-02 20:36:53.997826+00:00
[2023-11-02T20:38:13.407+0000] {standard_task_runner.py:57} INFO - Started process 122 to run task
[2023-11-02T20:38:13.411+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Google_Job_Listings_Data_Pipeline', 'feature_engineering', 'manual__2023-11-02T20:36:53.997826+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmpblbqalco']
[2023-11-02T20:38:13.413+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask feature_engineering
[2023-11-02T20:38:13.593+0000] {task_command.py:410} INFO - Running <TaskInstance: Google_Job_Listings_Data_Pipeline.feature_engineering manual__2023-11-02T20:36:53.997826+00:00 [running]> on host 1f525f761703
[2023-11-02T20:38:13.750+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Google_Job_Listings_Data_Pipeline' AIRFLOW_CTX_TASK_ID='feature_engineering' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T20:36:53.997826+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-02T20:36:53.997826+00:00'
[2023-11-02T20:38:13.753+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-02T20:38:13.755+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/extraction/feature_engineering.py 20231102']
[2023-11-02T20:38:13.773+0000] {subprocess.py:86} INFO - Output:
[2023-11-02T20:38:16.310+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-02T20:38:16.311+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/feature_engineering.py", line 15, in <module>
[2023-11-02T20:38:16.311+0000] {subprocess.py:93} INFO -     df = pd.read_csv(f'./tmp/{output_name}.csv')
[2023-11-02T20:38:16.312+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
[2023-11-02T20:38:16.312+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-11-02T20:38:16.313+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
[2023-11-02T20:38:16.314+0000] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2023-11-02T20:38:16.315+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
[2023-11-02T20:38:16.316+0000] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2023-11-02T20:38:16.316+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
[2023-11-02T20:38:16.317+0000] {subprocess.py:93} INFO -     self._engine = self._make_engine(self.engine)
[2023-11-02T20:38:16.319+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
[2023-11-02T20:38:16.321+0000] {subprocess.py:93} INFO -     return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
[2023-11-02T20:38:16.322+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
[2023-11-02T20:38:16.323+0000] {subprocess.py:93} INFO -     self._open_handles(src, kwds)
[2023-11-02T20:38:16.324+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
[2023-11-02T20:38:16.325+0000] {subprocess.py:93} INFO -     errors=kwds.get("encoding_errors", "strict"),
[2023-11-02T20:38:16.326+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
[2023-11-02T20:38:16.327+0000] {subprocess.py:93} INFO -     newline="",
[2023-11-02T20:38:16.328+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: './tmp/20231102.csv'
[2023-11-02T20:38:16.513+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-02T20:38:16.534+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-02T20:38:16.542+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Google_Job_Listings_Data_Pipeline, task_id=feature_engineering, execution_date=20231102T203653, start_date=20231102T203813, end_date=20231102T203816
[2023-11-02T20:38:16.569+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 51 for task feature_engineering (Bash command failed. The command returned a non-zero exit code 1.; 122)
[2023-11-02T20:38:16.596+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-11-02T20:38:16.635+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
