[2023-10-09T21:36:07.924+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-09T21:30:18.454206+00:00 [queued]>
[2023-10-09T21:36:07.937+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-09T21:30:18.454206+00:00 [queued]>
[2023-10-09T21:36:07.937+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-10-09T21:36:07.957+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): upload_to_s3> on 2023-10-09 21:30:18.454206+00:00
[2023-10-09T21:36:07.962+0000] {standard_task_runner.py:57} INFO - Started process 558 to run task
[2023-10-09T21:36:07.967+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Extract_job_data_in_selenium_container', 'upload_to_s3', 'manual__2023-10-09T21:30:18.454206+00:00', '--job-id', '729', '--raw', '--subdir', 'DAGS_FOLDER/extract_job_data_dag.py', '--cfg-path', '/tmp/tmp16anhnyw']
[2023-10-09T21:36:07.968+0000] {standard_task_runner.py:85} INFO - Job 729: Subtask upload_to_s3
[2023-10-09T21:36:08.023+0000] {task_command.py:410} INFO - Running <TaskInstance: Extract_job_data_in_selenium_container.upload_to_s3 manual__2023-10-09T21:30:18.454206+00:00 [running]> on host 18e533bd1f06
[2023-10-09T21:36:08.124+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Extract_job_data_in_selenium_container' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-10-09T21:30:18.454206+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-09T21:30:18.454206+00:00'
[2023-10-09T21:36:08.125+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-09T21:36:08.126+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/extraction/upload_aws_s3.py 20231009']
[2023-10-09T21:36:08.140+0000] {subprocess.py:86} INFO - Output:
[2023-10-09T21:36:08.590+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-09T21:36:08.591+0000] {subprocess.py:93} INFO -   File "/opt/***/extraction/upload_aws_s3.py", line 6, in <module>
[2023-10-09T21:36:08.591+0000] {subprocess.py:93} INFO -     from validation import validate_input
[2023-10-09T21:36:08.593+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'validation'
[2023-10-09T21:36:08.634+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-09T21:36:08.653+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-09T21:36:08.659+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=Extract_job_data_in_selenium_container, task_id=upload_to_s3, execution_date=20231009T213018, start_date=20231009T213607, end_date=20231009T213608
[2023-10-09T21:36:08.680+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 729 for task upload_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 558)
[2023-10-09T21:36:08.701+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-09T21:36:08.745+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
